services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    environment:
      - DRAGONFLY_PASSWORD=${DRAGONFLY_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - nvr-internal-network        
    command: ["/usr/local/bin/dragonfly", "--requirepass", "${DRAGONFLY_PASSWORD}"]
  
  nvrbuilder:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile_dev
    tty: true
    networks:
      - nvr-internal-network
    volumes:
      - ./code:/usr/smartnvr20
      - ./config_tests:/usr/local/etc/smartnvr20_tests
      - ./config:/usr/local/etc/smartnvr20
      
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    networks:
      - nvr-internal-network
    depends_on:
      - dragonfly

networks:
  nvr-internal-network:
    external: false
    name: nvr-internal-network