FROM dohtem81/gcc_opencv_base:latest
WORKDIR /usr/src

RUN apt-get update
RUN apt-get install build-essential autoconf libtool pkg-config -y

RUN git clone https://github.com/redis/hiredis.git
RUN mkdir /usr/src/hiredis/build
WORKDIR /usr/src/hiredis/build
RUN cmake ../.
RUN make
RUN make install
RUN make clean

WORKDIR /usr/src
RUN git clone https://github.com/gabime/spdlog.git
RUN mkdir /usr/src/spdlog/build
WORKDIR /usr/src/spdlog/build
RUN cmake ../.
RUN make
RUN make install
RUN make clean

WORKDIR /usr/src
RUN git clone https://github.com/nlohmann/json.git
RUN mkdir /usr/src/json/build
WORKDIR /usr/src/json/build
RUN cmake ../.
RUN make
RUN make install
RUN make clean

WORKDIR /usr/src
RUN git clone https://github.com/google/googletest.git /usr/src/googletest
WORKDIR /usr/src/googletest
RUN mkdir build
WORKDIR /usr/src/googletest/build
RUN cmake ../.
RUN make
RUN make install
RUN make clean

RUN apt-get install libssl-dev -y
WORKDIR /usr/src
RUN git clone --recurse-submodules -b v1.70.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc
WORKDIR /usr/src/grpc
RUN mkdir -p cmake/build
WORKDIR /usr/src/grpc/cmake/build
RUN cmake -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/usr/local ../..
RUN make
RUN make install
RUN make clean

RUN ldconfig

WORKDIR /usr/smartnvr20

CMD ["/bin/bash"]